# Makefile para compilar e rodar o projeto

JAVAC = javac
JAVA = java
CLASSES = FilaCircular.java Main.java
MAIN = Main

all: compile run

compile:
	$(JAVAC) $(CLASSES)

run:
	$(JAVA) $(MAIN)

clean:
	rm -f *.class
